const {chromium}=require('playwright');
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 await page.waitForFunction(()=>calReady&&calControls.length===13,null,{timeout:60000});
 const report=await page.evaluate(()=>calSerializable());
 assert(report.controls.every(c=>c.pass));assert.equal(report.results.length,30);assert.equal(report.sensitivityAudit.runs.length,360);
 assert(report.results.filter(r=>['gold','goldSwap','week','younger'].includes(r.method)).every(r=>r.matched===0));
 const checks=await page.evaluate(()=>runTests());assert(checks.slice(0,6).every(c=>c.accuracy===1));
 await page.selectOption('#calFilter','gold');assert.equal(await page.locator('#calResults tbody tr').count(),6);
 await page.getByText('Recorded sensitivity audit · 360 comparisons',{exact:true}).click();await page.selectOption('#calSweepFilter','55');assert.equal(await page.locator('#calSweepResults tbody tr').count(),24);
 await page.fill('#calText','ᚠ□ᚢᛜ');await page.click('#calTextRun');assert.match(await page.locator('#calTextResult').textContent(),/1 □ 2 □/);
 await page.selectOption('#calFilter','elder');await page.fill('#calText','ᛜᛝ');await page.click('#calTextRun');assert.match(await page.locator('#calTextResult').textContent(),/ŋ ŋ/);
 await page.selectOption('#calFilter','all');await page.click('#calControl');assert.match(await page.locator('#calTextResult').textContent(),/17 18 19/);
 await page.check('#calReverse');await page.click('#calRun');await page.waitForFunction(()=>calResults.length===30&&calResults.every(r=>r.direction==='reversed'));
 const reversed=await page.evaluate(()=>calSerializable());assert.deepEqual(reversed.results.map(r=>r.total),report.results.map(r=>r.total));
 await page.uncheck('#calReverse');await page.click('#calRun');await page.waitForFunction(()=>calResults.length===30&&calResults.every(r=>r.direction==='original'));
 const downloadPromise=page.waitForEvent('download');await page.click('#calExport');assert.equal((await downloadPromise).suggestedFilename(),'runic-calendar-experiment.json');
 assert.equal(await page.locator('#researchLetters tbody tr').count(),25);
 await page.selectOption('#researchBlock','BRAVE');assert.equal(await page.locator('#researchLetters tbody tr').count(),5);assert.match(await page.locator('#researchLetters').textContent(),/introdue/);
 await page.selectOption('#researchView','sources');assert(await page.locator('#researchSources').isVisible());assert.match(await page.locator('#researchSourceText').textContent(),/Unresolved/);
 await page.selectOption('#researchView','alignment');assert(await page.locator('#researchAlignment').isVisible());assert.equal(await page.locator('#researchWordTable tbody tr').count(),await page.evaluate(()=>researchWords.length-1));
 await page.selectOption('#researchWordFilter','differences');assert.equal(await page.locator('#researchWordTable tbody tr').count(),10);
 await page.selectOption('#researchWordFilter','uncertain');assert.equal(await page.locator('#researchWordTable tbody tr').count(),4);
 await page.selectOption('#researchView','files');assert.equal(await page.locator('#researchDownloads a').count(),7);
 const researchDownload=page.waitForEvent('download');await page.click('#researchExport');const researchFile=await researchDownload;assert.equal(researchFile.suggestedFilename(),'gravity-falls-research.json');const stream=await researchFile.createReadStream();let researchText='';for await(const chunk of stream)researchText+=chunk.toString();const research=JSON.parse(researchText);assert.equal(research.files.length,7);assert.equal(research.extraction.letterRecords.length,25);assert.equal(research.images.length,4);
 assert.equal(await page.locator('.segCard').count(),3);
 assert.match(await page.locator('#segAtlas').getAttribute('href'),/^data:image\/png;base64,/);
 assert.equal(await page.evaluate(()=>SEG.items.filter(item=>item.sample!==undefined).length),106);
 assert.equal(await page.evaluate(()=>SEG.groups.flatMap(group=>group.members).length),106);
 assert.equal(await page.evaluate(()=>new Set(SEG.groups.flatMap(group=>group.members)).size),106);
 assert.equal(await page.evaluate(()=>SEG.references.count),137);
 await page.selectOption('#segFilter','all');assert.equal(await page.locator('.segCard').count(),106);
 await page.selectOption('#segFilter','groups');assert.equal(await page.locator('.segCard').count(),49);
 await page.selectOption('#segFilter','unknown');await page.selectOption('#segRegion','Right border');assert.equal(await page.locator('.segCard').count(),1);
 await page.selectOption('#segFamily','Malachim');assert.equal(await page.locator('#segInventory details').count(),1);
 const segDownload=page.waitForEvent('download');await page.click('#segExport');assert.equal((await segDownload).suggestedFilename(),'image-segregation.json');
 await page.selectOption('#segRegion','all');await page.selectOption('#segFamily','all');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);require('node:fs').writeFileSync(path.resolve(__dirname,'../reports/browser-verification.json'),JSON.stringify({passed:true,calendarControls:13,sensitivityComparisons:360,checks:['six source samples reproduced','method filter','sensitivity filter','strict rune transcription','Ingwaz lookup','known control','reverse preserves counts','JSON export','390px mobile width','no browser errors','25 research letter records','research block filtering','source notes view','every word comparison','difference and uncertainty filters','seven offline research downloads','complete research JSON export','106 glyphs accounted for exactly once','49 shape groups','three unresolved objects','137 reference forms','segregation region and family filters','segregation JSON export','offline atlas download']},null,2));await browser.close();console.log('Passed calendar controls, 360-record audit, sample reproduction, filters, strict transcription, reversal, export and mobile width.');
})().catch(e=>{console.error(e);process.exit(1)});

