const CAL=DATA.calendar;
const CAL_METHODS=[{id:'gold',name:'Golden numbers · 1–19',kind:'numbers'},{id:'goldSwap',name:'Golden numbers · l/m order variant',kind:'numbers'},{id:'week',name:'Weekday row · A–G',kind:'cycle labels'},{id:'younger',name:'Younger Futhark · letters',kind:'transliteration'},{id:'elder',name:'Elder Futhark · comparison',kind:'transliteration'}];
const youngerNames=['fé','úr','þurs','óss','reið','kaun','hagall','nauðr','íss','ár','sól','Týr','bjarkan','maðr','lögr','ýr','Arlaug','Tvimadur','Belgthor'];
const youngerLatin=['f','u','þ','o','r','k','h','n','i','a','s','t','b','m','l','ʀ'];
const elderLatin=['f','u','þ','a','r','k','g','w','h','n','i','j','ï','p','z','s','t','b','e','m','l','ŋ','d','o'];
const calCanonical=new Map();Array.from(CAL.long).forEach((c,i)=>calCanonical.set(c,{index:i,name:youngerNames[i]}));Array.from(CAL.short).forEach((c,i)=>calCanonical.set(c,{index:i,name:youngerNames[i]}));
const elderMap=new Map(Array.from(CAL.elder).map((c,i)=>[c,elderLatin[i]]));elderMap.set('ᛝ','ŋ');
let calTemplates=[],calResults=[],calControls=[],calReview=null,calReady=false,calAnnotations=[];
function calLookup(c,method){if(method==='elder')return elderMap.get(c)??null;const item=calCanonical.get(c);if(!item)return null;let i=item.index;if(method==='week')return i<7?'ABCDEFG'[i]:null;if(method==='younger')return i<16?youngerLatin[i]:null;if(method==='goldSwap'&&(i===13||i===14))i=i===13?14:13;return i+1;}
function calTyped(text,method){const entries=Array.from(text).map((c,index)=>{if(/\s/.test(c)||[':', '᛫','᛬','᛭'].includes(c))return{index,char:c,separator:true,value:null};const value=calLookup(c,method);return{index,char:c,value,unknown:value===null};});const n=entries.filter(e=>!e.separator).length,matched=entries.filter(e=>!e.separator&&!e.unknown).length;return{method,input:text,entries,matched,total:n,coverage:n?matched/n:0,output:entries.map(e=>e.separator?' / ':e.unknown?'□':String(e.value)).join(' ').replace(/ +/g,' ').trim(),classification:method==='elder'?'Comparison alphabet; no calendar-number claim':'Key lookup; rune assignments require image evidence'};}
function calGlyphMatch(n,method){const options=[];for(const t of calTemplates){if(calLookup(t.char,method)===null)continue;const score=similarity(n.bits,t.bits)*Math.exp(-.08*Math.abs(Math.log(Math.max(.01,n.ratio)/Math.max(.01,t.ratio))));options.push({rune:t.char,canonical:method==='elder'?t.char:CAL.long[calCanonical.get(t.char).index],value:calLookup(t.char,method),score});}const groups=new Map();for(const o of options){const label=method==='elder'?o.value:String(o.value);if(!groups.has(label)||groups.get(label).score<o.score)groups.set(label,o);}return [...groups.values()].sort((a,b)=>b.score-a.score).slice(0,3);}
function calSampleGeometry(c,sampleIndex){const threshold=sampleIndex===4?15:sampleIndex===5?4:5,p=preprocess(c,threshold),layout=CAL.layouts[sampleIndex];return layout.map((g,i)=>({...normalize(p.m,p.w,p.h,g.a,g.b),index:i,x:g.a,width:g.b-g.a,separator:g.separator}));}
function calCropGeometry(c){const p=preprocess(c,+$('contrast').value),col=new Int32Array(p.w);for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++)col[x]+=p.m[y*p.w+x];return ranges([...col].map(v=>v>1)).map(([a,b],i)=>{const n=normalize(p.m,p.w,p.h,a,b);return{...n,index:i,x:a,width:b-a,separator:false};});}
function calRunGeometry(geometry,method,name,reverse=false){const min=+$('calAccept').value/100,margin=+$('calMargin').value/100,source=reverse?[...geometry].reverse():geometry;const entries=source.map((g,index)=>{if(g.separator)return{index,sourceIndex:g.index,separator:true,rune:':',value:null,bits:g.bits};const alternatives=calGlyphMatch(g,method),top=alternatives[0],lead=top?top.score-(alternatives[1]?.score||0):0,accepted=!!top&&top.score>=min&&lead>=margin;return{index,sourceIndex:g.index,x:g.x,width:g.width,rune:accepted?top.rune:'□',value:accepted?top.value:null,unknown:!accepted,score:top?.score||0,lead,alternatives,bits:g.bits,status:accepted?'tentative shape match':'unresolved'};});const total=entries.filter(e=>!e.separator).length,matched=entries.filter(e=>!e.separator&&!e.unknown).length;return{section:name,method,methodName:CAL_METHODS.find(m=>m.id===method).name,direction:reverse?'reversed':'original',minScore:min,minLead:margin,total,matched,coverage:total?matched/total:0,transcription:entries.map(e=>e.separator?':':e.rune).join(''),output:entries.map(e=>e.separator?' / ':e.unknown?'□':String(e.value)).join(' ').replace(/ +/g,' ').trim(),entries,evidence:'Template resemblance only; not verified rune identities',dateInferred:null};}
async function calRunSamples(){if(!calReady)return;calResults=[];$('calStatus').textContent='Testing the six supplied crops with shared glyph boundaries…';for(let i=0;i<DATA.samples.length;i++){const c=await loadImage(DATA.samples[i].image),g=calSampleGeometry(c,i);for(const m of CAL_METHODS)calResults.push({...calRunGeometry(g,m.id,DATA.samples[i].name,$('calReverse').checked),sample:i});await new Promise(resolve=>setTimeout(resolve,0));}calRender();calLoadSelected();$('calStatus').textContent=calResults.length+' section/method comparisons complete. All unknown positions retained.';return calResults;}
function calRender(){const method=$('calFilter').value,rs=calResults.filter(r=>method==='all'||r.method===method);$('calResults').innerHTML='<table><thead><tr><th>Section / method</th><th>Candidate runes</th><th>Output values</th><th>Shape coverage</th></tr></thead><tbody>'+rs.map(r=>'<tr data-cal-index="'+calResults.indexOf(r)+'" style="cursor:pointer"><td>'+escapeText(r.section)+'<br><small>'+escapeText(r.methodName)+'</small></td><td class="runic-font">'+escapeText(r.transcription)+'</td><td>'+escapeText(r.output)+'</td><td>'+r.matched+'/'+r.total+' · '+Math.round(r.coverage*100)+'%<br><small>tentative</small></td></tr>').join('')+'</tbody></table>';for(const row of $('calResults').querySelectorAll('tr[data-cal-index]'))row.onclick=()=>{const r=calResults[+row.dataset.calIndex];calSetReview(r);$('calSection').value=String(r.sample??'crop');};const calendar=calResults.filter(r=>r.method!=='elder'&&r.method!=='younger');let best=calendar.reduce((a,b)=>b.coverage>a.coverage?b:a,{coverage:0});$('calVerdict').textContent=calendar.length?'No complete calendar reading established. Best section coverage: '+Math.round(best.coverage*100)+'% under the selected matching thresholds. These are tentative visual matches; no date has been derived.':'No calendar experiment has been run.';}
function calSetReview(r){calReview=r;$('calText').value=r.transcription;$('calGlyphs').replaceChildren();for(const e of r.entries){const b=document.createElement('button');b.className='glyph'+(e.unknown?' low':'');b.append(bitsCanvas(e.bits));const d=document.createElement('div');d.className='letter runic-font';d.textContent=e.rune;b.append(d);const small=document.createElement('small');small.textContent=e.separator?'separator':Math.round(e.score*100)+'%';b.append(small);b.title=e.alternatives?.map(a=>a.rune+' '+Math.round(a.score*100)+'% → '+a.value).join(' · ')||'Observed separator';b.onclick=()=>{const details=e.alternatives?.map(a=>a.rune+' = '+a.value+' ('+Math.round(a.score*100)+'%)').join(' · ')||'Word separator';$('calStatus').textContent='Glyph '+(e.sourceIndex+1)+': '+details+'. Edit the transcription to annotate a choice.';};$('calGlyphs').append(b);}calInterpretTyped(false);}
function calLoadSelected(){const i=+$('calSection').value,m=$('calFilter').value==='all'?'gold':$('calFilter').value,r=calResults.find(r=>r.sample===i&&r.method===m)||calResults.find(r=>r.sample===i);if(r)calSetReview(r);}
function calInterpretTyped(record=true){const text=$('calText').value,ids=$('calFilter').value==='all'?CAL_METHODS.map(m=>m.id):[$('calFilter').value],results=ids.map(m=>calTyped(text,m));$('calTextResult').innerHTML='<table><thead><tr><th>Interpretation</th><th>Output</th><th>Recognized key entries</th></tr></thead><tbody>'+results.map(r=>'<tr><td>'+escapeText(CAL_METHODS.find(m=>m.id===r.method).name)+'</td><td>'+escapeText(r.output)+'</td><td>'+r.matched+'/'+r.total+'</td></tr>').join('')+'</tbody></table><p class="muted">Typed rune assignments are user annotations. Unknown or out-of-key characters are retained as □. This lookup is not an image-identification test.</p>';if(record)calAnnotations.push({text,section:calReview?.section||'typed',results,time:new Date().toISOString()});return results;}
function goldenNumber(year){if(!Number.isInteger(year)||year<1||year>9999)throw Error('Year must be between 1 and 9999.');return year%19+1;}
function dateCheck(iso){if(!/^\d{4}-\d{2}-\d{2}$/.test(iso))throw Error('Use a valid YYYY-MM-DD date.');const [year,month,day]=iso.split('-').map(Number);if(year<1||year>9999)throw Error('Year must be between 1 and 9999.');const d=new Date(0);d.setUTCFullYear(year,month-1,day);d.setUTCHours(0,0,0,0);if(d.getUTCFullYear()!==year||d.getUTCMonth()!==month-1||d.getUTCDate()!==day)throw Error('Invalid Gregorian date.');return{date:iso,weekday:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d.getUTCDay()],goldenNumber:goldenNumber(year),system:'Modern Gregorian date arithmetic; no staff date reconstruction'};}
function showDateCheck(){try{const r=dateCheck($('calDate').value);$('calDateResult').textContent=r.date+' · '+r.weekday+' · golden number '+r.goldenNumber+'. This is a year-cycle check, not a date extracted from the image.';}catch(e){$('calDateResult').textContent=e.message;}}
async function calRunControls(){const out=[],add=(name,pass,actual,expected)=>out.push({name,pass,actual,expected});let a=calTyped(CAL.long,'gold');add('19-rune exact key',a.output===Array.from({length:19},(_,i)=>i+1).join(' '),a.output,'1 through 19');a=calTyped(CAL.short,'gold');add('Short-twig variants',a.matched===16,a.output,'1 through 16');a=calTyped(CAL.long.slice(0,7),'week');add('Weekday row labels',a.output==='A B C D E F G',a.output,'A B C D E F G');a=calTyped('ᛜᛝ','gold');add('Ingwaz excluded from calendar',a.matched===0&&a.total===2,a.output,'□ □');a=calTyped('ᛜᛝ','elder');add('Ingwaz Elder comparison',a.output==='ŋ ŋ',a.output,'ŋ ŋ');a=calTyped('ᚠ□ᚢ','gold');add('Unknown position retained',a.output==='1 □ 2'&&a.total===3,a.output,'1 □ 2');a=calTyped('◇△A','gold');add('Lookalikes and Latin letters rejected',a.matched===0&&a.total===3,a.output,'□ □ □');a=calTyped('ᛮᛯᛰ','gold');add('Extra calendar signs',a.output==='17 18 19',a.output,'17 18 19');a=calTyped('ᛘᛚ','goldSwap');add('l/m order variant',a.output==='15 14',a.output,'15 14');add('2020 date checks',dateCheck('2020-11-03').weekday==='Tuesday'&&dateCheck('2020-05-25').weekday==='Monday'&&goldenNumber(2020)===7,JSON.stringify([dateCheck('2020-11-03'),dateCheck('2020-05-25')]),'Tuesday; Monday; golden number 7');add('19-year cycle',goldenNumber(2039)===goldenNumber(2020),goldenNumber(2039),7);let rejected=false;try{dateCheck('2020-02-30')}catch(e){rejected=true;}add('Invalid date rejected',rejected,rejected,true);
const img=await loadImage(CAL.controlImage),g=calCropGeometryForControl(img),r=calRunGeometry(g,'gold','Reference font control',false);const normalized=r.transcription.replace(/:/g,'');add('Reference-font image control',normalized===CAL.long,normalized,CAL.long);calControls=out;$('calTestResults').innerHTML='<table><thead><tr><th>Control</th><th>Actual</th><th>Status</th></tr></thead><tbody>'+out.map(o=>'<tr><td>'+escapeText(o.name)+'</td><td class="runic-font">'+escapeText(o.actual)+'</td><td class="'+(o.pass?'pass':'fail')+'">'+(o.pass?'PASS':'FAIL')+'</td></tr>').join('')+'</tbody></table>';return out;}
function calCropGeometryForControl(c){const p=preprocess(c,12),col=new Int32Array(p.w);for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++)col[x]+=p.m[y*p.w+x];return ranges([...col].map(v=>v>1)).map(([a,b],i)=>({...normalize(p.m,p.w,p.h,a,b),index:i,x:a,width:b-a,separator:false}));}
function calRenderSweep(){const score=+$('calSweepFilter').value/100,method=$('calSweepMethod').value,rows=CAL.sensitivityAudit.runs.filter(r=>r.minScore===score&&r.method===method);$('calSweepResults').innerHTML='<table><thead><tr><th>Section / orientation</th><th>Output</th><th>Shape coverage</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+escapeText(r.section)+'<br><small>'+escapeText(r.orientation)+'</small></td><td>'+escapeText(r.output)+'</td><td>'+r.matched+'/'+r.total+' · '+Math.round(r.coverage*100)+'%</td></tr>').join('')+'</tbody></table>';}
function calSerializable(){return{version:1,created:new Date().toISOString(),settings:{minScore:+$('calAccept').value/100,minLead:+$('calMargin').value/100,reverse:$('calReverse').checked},results:calResults.map(r=>({...r,entries:r.entries.map(e=>({...e,bits:Array.from(e.bits)}))})),controls:calControls,sensitivityAudit:CAL.sensitivityAudit,annotations:calAnnotations,dateChecks:['2020-05-25','2020-11-03','1865-12-18'].map(dateCheck),sources:CAL.sources,conclusion:'No verified calendar interpretation or hidden date established. Image rune assignments remain tentative.'};}
async function initializeCalendar(){while(!currentResult)await new Promise(resolve=>setTimeout(resolve,25));const style=document.createElement('style');style.textContent='@font-face{font-family:RunicLocal;src:url(data:font/ttf;base64,'+CAL.font+')} .runic-font{font-family:RunicLocal,system-ui,sans-serif}#calResults td{max-width:360px;overflow-wrap:anywhere}#calResults tr[data-cal-index]:hover{background:#2b352a}';document.head.append(style);for(const t of CAL.templates){const c=await loadImage(t.image),p=preprocess(c,12),d=p.c.getContext('2d').getImageData(0,0,p.w,p.h).data;for(let i=0;i<p.m.length;i++)p.m[i]=d[i*4]<105?1:0;const n=normalize(p.m,p.w,p.h,0,p.w);calTemplates.push({...t,...n});}
$('calSection').innerHTML=DATA.samples.map((s,i)=>'<option value="'+i+'">'+escapeText(s.name)+'</option>').join('');$('calSection').value='3';$('calSources').innerHTML=CAL.sources.map(s=>'<p><a target="_blank" rel="noopener" href="'+escapeText(s.url)+'">'+escapeText(s.title)+'</a></p>').join('');$('calKeyTable').innerHTML='<table><thead><tr><th>Rune</th><th>Name</th><th>Golden number</th><th>Weekday-row label</th></tr></thead><tbody>'+Array.from(CAL.long).map((c,i)=>'<tr><td class="runic-font">'+c+'</td><td>'+escapeText(youngerNames[i])+'</td><td>'+(i+1)+'</td><td>'+(i<7?'ABCDEFG'[i]:'—')+'</td></tr>').join('')+'</tbody></table>';$('calVisibleDates').innerHTML='<table><thead><tr><th>Artwork date / reference date</th><th>Weekday</th><th>Golden number</th></tr></thead><tbody>'+['2020-05-25','2020-11-03','1865-12-18'].map(iso=>{const r=dateCheck(iso);return'<tr><td>'+iso+(iso.startsWith('1865')?' (Amendment reference; artwork only shows 1865)':'')+'</td><td>'+r.weekday+'</td><td>'+r.goldenNumber+'</td></tr>';}).join('')+'</tbody></table>';calReady=true;calRenderSweep();showDateCheck();await calRunSamples();await calRunControls();}
$('calRun').onclick=calRunSamples;$('calCrop').onclick=()=>{if(!working||!calReady)return;if(working.height>120&&working.width/working.height<5){$('calStatus').textContent='Select a single symbol line before testing the current crop.';return;}const g=calCropGeometry(working);calResults=CAL_METHODS.map(m=>calRunGeometry(g,m.id,'Current crop',$('calReverse').checked));calRender();calSetReview(calResults.find(r=>r.method===($('calFilter').value==='all'?'gold':$('calFilter').value))||calResults[0]);$('calStatus').textContent='Current crop compared with all five interpretations. Generic crop segmentation is automatic; inspect split or joined glyphs.';};$('calFilter').onchange=()=>{calRender();calLoadSelected();if(!$('calText').value)return;calInterpretTyped(false);};$('calUse').onclick=calLoadSelected;$('calSection').onchange=calLoadSelected;$('calControl').onclick=()=>{$('calText').value=CAL.long;calInterpretTyped(false);};$('calTextRun').onclick=()=>calInterpretTyped(true);$('calExport').onclick=()=>download('runic-calendar-experiment.json',calSerializable());$('calDateCheck').onclick=showDateCheck;$('calTests').onclick=calRunControls;for(const id of ['calAccept','calMargin'])$(id).oninput=()=>$(id+'Value').textContent=$(id).value;
$('calSweepFilter').onchange=calRenderSweep;$('calSweepMethod').onchange=calRenderSweep;
initializeCalendar();

