const RESEARCH=__RESEARCH_DATA__;
function researchTable(headers,rows){return '<table><thead><tr>'+headers.map(h=>'<th>'+escapeText(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td style="white-space:pre-wrap">'+escapeText(String(v??''))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function researchRenderLetters(){const block=$('researchBlock').value,rows=RESEARCH.extraction.letterRecords.filter(r=>block==='all'||r.block===block);$('researchLetters').innerHTML=researchTable(['Position','Title letter','Image transcription','Confidence'],rows.map(r=>[r.index,r.block+' · '+r.displayLetter,r.transcription,r.confidence]));}
function researchCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
const researchWords=researchCSV(RESEARCH.files.find(f=>f.name==='whitepaper-every-word-alignment.csv').text);
function researchRenderWords(){const filter=$('researchWordFilter').value,rows=researchWords.slice(1).filter(r=>filter==='all'||filter==='differences'&&r[3].includes('review required')||filter==='uncertain'&&(r[1].includes('UNCERTAIN')||r[1].includes('UNREADABLE')));$('researchWordTable').innerHTML=researchTable(['Image word position','Image token','Reference word position','Status','Reference difference'],rows);}
function researchChangeView(){for(const [id,value] of [['researchWhitepaper','whitepaper'],['researchSources','sources'],['researchAlignment','alignment'],['researchFiles','files'],['segregationPanel','segregation'],['globalCatalogPanel','global'],['decipherPanel','decipher']])$(id).hidden=$('researchView').value!==value;}
$('researchFooter').textContent=RESEARCH.extraction.footer;
$('researchSourceText').textContent=RESEARCH.sourceNotes;
$('researchDifferences').innerHTML=researchTable(['Location','Artwork','Reference','Assessment'],RESEARCH.extraction.comparison.map(r=>[r.location,r.image,r.reference,r.assessment]));
$('researchImages').innerHTML=RESEARCH.images.map(i=>'<p>'+escapeText(i.label)+'</p><img alt="'+escapeText(i.label)+' enlarged artwork strip" src="'+i.data+'" style="max-width:100%;height:auto">').join('');
$('researchAlignmentNote').textContent=RESEARCH.alignment.referenceTokens+' reference tokens; '+RESEARCH.alignment.provisionalImageTokensAfterExplicitFragmentJoining+' provisional image tokens after explicit fragment joining; '+RESEARCH.alignment.alignedEqualTokensIgnoringCase+' equal tokens ignoring case. Reference: section 2, Transactions, printed page 2.';
for(const file of RESEARCH.files){const a=document.createElement('a');a.textContent=file.name.replace(/-/g,' ');a.download=file.name;a.href=URL.createObjectURL(new Blob([file.text],{type:'text/plain;charset=utf-8'}));$('researchDownloads').appendChild(a);}
$('researchView').onchange=researchChangeView;$('researchBlock').onchange=researchRenderLetters;$('researchWordFilter').onchange=researchRenderWords;$('researchExport').onclick=()=>download('gravity-falls-research.json',{...RESEARCH,segregation:SEG,globalCatalog:GLOBALCAT,decipherment:DECIPHER});
researchRenderLetters();researchRenderWords();researchChangeView();
